apiVersion: apps/v1
kind: Deployment
metadata:
  name: poller
  namespace: kube-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poller
  template:
    metadata:
      labels:
        app: poller
    spec:
      containers:
        - name: poller
          image: poller:v1
          imagePullPolicy: Never
          env:
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-password
          ports:
            - containerPort: 8080
